package exceptionDemo_;

public class SingleCatchDemo {
	public static void main(String[] args) {
		System.out.println("开始---------------------");
		try {
		int tt = 10/0;
		System.out.println("结果=" + tt);
		} catch (ArithmeticException e) {
			// TODO: handle exception
			
		}
		
		System.out.println("结束---------------------");
	}
}
